### PR TITLE
nix-on-droid: add -I argument

### PR DESCRIPTION
**Pull request by Gerschtli**
Pass -I argument to nix-build.

Closes https://github.com/t184256/nix-on-droid-bootstrap/issues/40

### CODE REVIEW

**Comment by Gerschtli** [comment]
Ah yes, the `<nix-on-droid>` one needs the `NIX_PATH` info, will fix it tomorrow

**Comment by Gerschtli** [comment]
Ah wait a second: my changes are working as expected, you missed the `nix-on-droid=` prefix in your command:

```diff
-nix-on-droid -I $(pwd) switch
+nix-on-droid -I nix-on-droid=$(pwd) switch
```

**Comment by t184256** [comment]
Yeah, you're right, my bad. Seems to work OK if used properly.

And now it feels weird that the repository name isn't 'nix-on-droid'. Hope it won't be too confusing later.

**Comment by Gerschtli** [comment]
Maybe we should consider renaming it because the name does not longer match the content..

As this is still in a very early stage, better do it now than later. Don't know how to let the user know that the channel url has changed. Maybe redirect old channel url to the new one.

**Comment by t184256** [comment]
Seems like it's a pretty straightforward low-risk thing, huh. Feeling courageous today, renamed.

**Pull request merged**
